[package]
name = "json-arrays"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1"
serde_json = "1"

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
